//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Envision.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnvisionEntities : DbContext
    {
        public EnvisionEntities()
            : base("name=EnvisionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applied> Applieds { get; set; }
        public virtual DbSet<CategoriesList> CategoriesLists { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyIndustry> CompanyIndustries { get; set; }
        public virtual DbSet<DegreeList> DegreeLists { get; set; }
        public virtual DbSet<IndustryList> IndustryLists { get; set; }
        public virtual DbSet<Internship> Internships { get; set; }
        public virtual DbSet<InternshipLocation> InternshipLocations { get; set; }
        public virtual DbSet<InternshipPerk> InternshipPerks { get; set; }
        public virtual DbSet<InternshipSkill> InternshipSkills { get; set; }
        public virtual DbSet<LocationsList> LocationsLists { get; set; }
        public virtual DbSet<PerksList> PerksLists { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectUser> ProjectUsers { get; set; }
        public virtual DbSet<SkilledIn> SkilledIns { get; set; }
        public virtual DbSet<SkillsList> SkillsLists { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Studied> Studieds { get; set; }
        public virtual DbSet<TasksList> TasksLists { get; set; }
        public virtual DbSet<VolunteerWork> VolunteerWorks { get; set; }
        public virtual DbSet<WorkExperience> WorkExperiences { get; set; }
        public virtual DbSet<RoleList> RoleLists { get; set; }
        public virtual DbSet<Join> Joins { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<ProjectTask> ProjectTasks { get; set; }
        public virtual DbSet<TasksAssigned> TasksAssigneds { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<AdminQuery> AdminQueries { get; set; }
    }
}