//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Envision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternshipSkill
    {
        public string I_Id { get; set; }
        public int S_Id { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Internship Internship { get; set; }
        public virtual SkillsList SkillsList { get; set; }
    }
}
