//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Envision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public string UserId { get; set; }
        public string UserType { get; set; }
        public string Link { get; set; }
        public System.DateTime Time { get; set; }
        public string IP { get; set; }
        public string HostName { get; set; }
    }
}
