//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Envision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectTask()
        {
            this.TasksAssigneds = new HashSet<TasksAssigned>();
        }
    
        public string Id { get; set; }
        public string P_Id { get; set; }
        public int T_Id { get; set; }
        public System.DateTime DeadLine { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual TasksList TasksList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TasksAssigned> TasksAssigneds { get; set; }
    }
}
