//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Envision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectUser()
        {
            this.TasksAssigneds = new HashSet<TasksAssigned>();
        }
    
        public string Id { get; set; }
        public string P_Id { get; set; }
        public string U_Id { get; set; }
        public int R_Id { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Student Student { get; set; }
        public virtual RoleList RoleList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TasksAssigned> TasksAssigneds { get; set; }
    }
}
