//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Envision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkilledIn
    {
        public string U_Id { get; set; }
        public int S_ID { get; set; }
        public decimal Value { get; set; }
    
        public virtual SkillsList SkillsList { get; set; }
        public virtual Student Student { get; set; }
    }
}
