//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Envision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studied
    {
        public string S_Id { get; set; }
        public string Name { get; set; }
        public string GoogleId { get; set; }
        public int Degree { get; set; }
        public Nullable<decimal> GraduationYear { get; set; }
    
        public virtual DegreeList DegreeList { get; set; }
        public virtual Student Student { get; set; }
    }
}
