//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Envision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasksAssigned
    {
        public string PU_Id { get; set; }
        public string PT_Id { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual ProjectTask ProjectTask { get; set; }
        public virtual ProjectUser ProjectUser { get; set; }
    }
}
